# -*- coding: utf-8 -*-
# author: Jakub Skałecki (jakub.skalecki@gmail.com)

SITE_ROOT = 'STATIC_ROOT'
STATIC_FOLDER = 'DIST'

BACKEND_URL = 'BACKEND_URL'
BACKEND_LOGIN = 'BACKEND_LOGIN'
BACKEND_PASS = 'BACKEND_PASS'

LOG_LEVEL = 'LOG_LEVEL'

DEBUG = 'DEBUG'

SECRET_KEY = 'SECRET_KEY'

LANGUAGES = 'LANGUAGES'

TESTING = 'TESTING'

MOCK_API = 'MOCK_API'

CLOUDINARY_PUBLIC_KEY = 'CLOUDINARY_API_KEY'
CLOUDINARY_CLOUD_NAME = 'CLOUDINARY_CLOUD'
CLOUDINARY_SECRET = 'CLOUDINARY_SECRET'
